language: node_js
before_script:
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- ./prebuild.sh
script:
- docpad deploy-ghpages
env:
  global:
  - FOO="BAR"
  - GH_REPO="medevice-users/gallery"
  - secure: aMM5TtJlbdW8KWQRsyeoJRvPtk07Vn58T9yigJo1NxEikUHChZhUrkugkFEwhZcjwSgRFcvVCrcK6EUwl6Gk48Rxr9nXX0GB7LaCNLXxtcBIvkfaXCzWdSKfzC9hMuOOOOF2lk/Qp6INGSIaAa0JQmI6wzzQj4uBl/+9dENKjio=
