language: node_js
before_script:
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- ./prebuild.sh
script:
- docpad deploy-ghpages
env:
  global:
  - FOO="BAR"
  - GH_REPO="medevice-users/gallery"
  - secure: fNWJdXAU8jtfZtS4IFMuCHZvkyni7gUs7RpjI/41WVZpjtfsyJjeXKmnafDpLcgp10zg7mQ2upmIOtS2TtmSy+40gmKscKzvWN/lQaZSW1g0RQfbIIYMgq5Jz2PtFg6E0yFyovN25Ze0fcRFQOAcFSgBq+v4KrMVqpUfAOumz5I=
