
language: node_js
before_script:
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - git remote rename origin source
  - git remote add origin $REPO_URL
script:
  - docpad deploy-ghpages
env:
  global:
    - FOO="BAR"
    - GH_REPO="medevice-users/gallery"
    - secret="JXAcNcWpPMqqmjOZ+wbZvdquk/yeUT9pgpHRo4X5BDOiCaVhAYzEsqlgI5poWfSbHHfhcqnbYmsqUNtzHDimRoABoYVVbytD4o57Bo2jukDyNgZFHOrCtKUUOojU60avb876FhtBuCYcb/DoDWFY3qAZhvplunC4v4c5gt5XSKk="

