language: node_js
before_script:
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- git config user.email 'bewest+insulaudit@gmail.com'
- git config user.name 'Ben West [via travis]'
- git remote rename origin source
- git remote add origin $REPO_URL
script:
- docpad deploy-ghpages
env:
  global:
  - FOO="BAR"
  - GH_REPO="medevice-users/gallery"
  - secure: SKM4QwO2fa7HBM0M6174mjehFCAV0Fy6cqR9EHvEs8eixFVerepHoIGeK7z/NpAcJgTLMt2mJmWI+KBF4/kva2SUJq3OKZ/MiZtDSWjveTTRaERZIoVBLdLYA6Y/eplD42EkbYYuCyOGDy7POTxDWk9iVuaZvhEnSt1I+OdMFB0=
