language: node_js
before_script:
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- ./prebuild.sh
script:
- docpad deploy-ghpages
env:
  global:
  - FOO="BAR"
  - GH_REPO="medevice-users/gallery"
  - secure: SKM4QwO2fa7HBM0M6174mjehFCAV0Fy6cqR9EHvEs8eixFVerepHoIGeK7z/NpAcJgTLMt2mJmWI+KBF4/kva2SUJq3OKZ/MiZtDSWjveTTRaERZIoVBLdLYA6Y/eplD42EkbYYuCyOGDy7POTxDWk9iVuaZvhEnSt1I+OdMFB0=
  - secure: Kli7XYXWxlGa2J8CZBrN0G7YGvCOBRP8Ej55fGuJgQsEF5xJCjgAd61psyvzsFiidh1fqcTE0HI1TJvwMVv5jHnSv+8yPb/V1/EIHw0+ssndcL35N7bxejWU6Z5vPyVO9OCOnCiaZTQkckNvPsQ1DxE7lu49k3HhUSpzN9h8bCE=
