
prose:
  rooturl: "src/documents"
  metadata:
    "src/documents/posts": |
      title: "Title of your article"
      layout: 'post'
      tags: ['dashboard','post']
      thumbnail_url: http://diabetesvisualization.t1dtechnology.info/wp-content/uploads/2013/07/medtronic-dashboard-314x224.png
      survey: https://docs.google.com/forms/d/1F5SEFNx5W_-hKY065uiwQdAaSjq2Q259NdmKNhXiwcI/viewform#_

    "src/documents/pages": |
      title: "New page name"
      layout: page
      pageOrder: 1
      tags: 
        - about
        - page
      published: true

